// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FluentMigrator.T4.GenerateMigration
{
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.Common;
    using System.Diagnostics;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Configuration;
    using System.Windows.Forms;
    using FluentMigrator.T4;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class InitialMigrationCode : InitialMigrationCodeBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

/*
T4 Template for importing the DB structure for the Fluent Migration. Adapted from PetaPoco/Subsonic T4 code.
Created by Guru Kathiresan - gururamnath  -att-   yahoo.com
-----------------------------------------------------------------------------------------
 
Features
=========
* Generate Intial Table structure for all support DB
* Support for Index code generation for SQLite DB

Todo
====

1) Ability to import other DB items like Triggers/Procedures/etc..
2) Abiity add the intial setup data
3) Generated ForeignKey code does not work for SQLite. FM problem ?
3) Generated ForeignKey and Index code for Oracle/MSSQL/MSSQL Compact/MySQL/PGSQL
*/


            
            #line default
            #line hidden
            
            #line 21 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"


    // Settings
    ConnectionStringName = "";			// Uses last connection string in config if not specified
    Namespace = "Migrations";
    ClassPrefix = "";
    ClassSuffix = "";
    IncludeViews = false;
    
    var generator = new CodeGenerator(ConnectionString, ProviderName, new DelegateTextWriter(x=>WriteLine(x)), s=>Warning(s));


    // Read schema
    var tables = generator.LoadTables();
	foreach (Table aTable in tables)
	{
		var oldTable = IgnoreInfo.SingleOrDefault(t => t.Name == aTable.Name);
		if (oldTable == null) continue;
		foreach (Column aColumn in aTable.Columns)
		{
			var oldCol = oldTable.Columns.SingleOrDefault(c => c.Name == aColumn.Name);
			if (oldCol == null) continue;
			aColumn.Ignore = true;
		}
	}

    // Generate output


            
            #line default
            #line hidden
            
            #line 49 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"


if (string.IsNullOrEmpty(Namespace)) Namespace=ConnectionStringName;
if (string.IsNullOrEmpty(Namespace)) Namespace="FluentMigration";

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Web;\r\nusing System.Linq.Expressions;\r\nusing FluentMigrator;\r\n\r\nnamespace ");
            
            #line 61 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Migration(");
            
            #line 63 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCurrentTimeStamp()));
            
            #line default
            #line hidden
            this.Write(")]\r\n    public class CreateInitialDb");
            
            #line 64 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetCurrentTimeStamp()));
            
            #line default
            #line hidden
            this.Write(" : Migration\r\n    {\r\n");
            
            #line 66 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
//begin the up migration definition

            
            #line default
            #line hidden
            this.Write("        public override void Up()\r\n        {\r\n");
            
            #line 69 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
//main loop to handle new or changed tables
foreach(Table tbl in from t in tables where !t.Ignore select t)
{
//Note if the table is already present, and thus was altered, so we can change how columns are created - Alter instead of Create statements
bool isAlter = IgnoreInfo.Any(t => t.Name == tbl.Name);
var ColumnList = from c in tbl.Columns where !c.Ignore select c;
if (ColumnList.Any()) //create the table if it didn't exist, and add all/missing columns
{
            
            #line default
            #line hidden
            this.Write("            //For ");
            
            #line 77 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isAlter ? "Alter" : "Create"));
            
            #line default
            #line hidden
            this.Write(".Table(\"");
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(tbl.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 78 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

    
foreach(Column col in ColumnList)
{

            
            #line default
            #line hidden
            this.Write("\r\n                .");
            
            #line 84 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isAlter ? "Add" : "With"));
            
            #line default
            #line hidden
            this.Write("Column(\"");
            
            #line 84 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\").");
            
            #line 84 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetMigrationTypeFunctionForType(col)));
            
            #line default
            #line hidden
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsPrimaryKey){
            
            #line default
            #line hidden
            this.Write(".PrimaryKey()");
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsAutoIncrement){
            
            #line default
            #line hidden
            this.Write(".Identity()");
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsNullable){
            
            #line default
            #line hidden
            this.Write(".Nullable()");
            
            #line 85 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
} 
else {
            
            #line default
            #line hidden
            this.Write(".NotNullable()");
            
            #line 86 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 86 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.DefaultValue != null || (!col.IsNullable && isAlter)){
            
            #line default
            #line hidden
            
            #line 86 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetColumnDefaultValue(col)));
            
            #line default
            #line hidden
            
            #line 86 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 87 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 91 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}//create the indexes for any new or changed tables
//not currently handling indexes on pre-existing tables
foreach(TableIndex indx in tbl.Indexes)
{

            
            #line default
            #line hidden
            this.Write("            Create.Index(\"");
            
            #line 96 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indx.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 96 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 96 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(tbl.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 96 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 96 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 97 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

foreach(IndexColumn col in indx.IndexColumns)
{

            
            #line default
            #line hidden
            this.Write("\r\n                .OnColumn(\"");
            
            #line 102 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 102 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsAsc){
            
            #line default
            #line hidden
            this.Write(".Ascending()");
            
            #line 102 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}else{
            
            #line default
            #line hidden
            this.Write(".Descending()");
            
            #line 102 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 103 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            
            #line 105 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (indx.IsUnique){

            
            #line default
            #line hidden
            this.Write("\r\n                .WithOptions().Unique()");
            
            #line 108 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 109 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}
//if the table was pre-existing, delete any columns that were deleted, along with their foreign keys, if any
if (isAlter)
{
	foreach (var deleteColumn in IgnoreInfo.Single(t => t.Name == tbl.Name).Columns.Where(c => !tbl.Columns.Any(col => col.Name == c.Name)))
	{
		ForeignKey columnForeignKey = IgnoreInfo.Single(t => t.Name == tbl.Name).ForeignKeys.FirstOrDefault(fk => fk.PrimaryColumns.Any(pc => pc == deleteColumn.Name));
		if (columnForeignKey != null)
		{

            
            #line default
            #line hidden
            this.Write("            Delete.ForeignKey(\"");
            
            #line 120 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnForeignKey.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 120 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"dbo\"); \r\n");
            
            #line 121 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\tDelete.Column(\"");
            
            #line 124 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deleteColumn.Name));
            
            #line default
            #line hidden
            this.Write("\").FromTable(\"");
            
            #line 124 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"dbo\");\r\n");
            
            #line 125 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

	}
}
}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 131 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

bool commentAlreadyWritten = false;
//handle added foreign keys
foreach(Table tbl in from t in tables where !t.Ignore select t)
{
Table otherTable = IgnoreInfo.SingleOrDefault(ot => ot.Name == tbl.Name);
List<ForeignKey> FKeyList = tbl.ForeignKeys;
if (otherTable != null) //if the table is pre-existing, filter out any foreign keys that were already present
{
    FKeyList = FKeyList.Where(nfk => otherTable.ForeignKeys.All(ofk => ofk.Name != nfk.Name)).ToList();
}
foreach(ForeignKey fkey in FKeyList)
{

            
            #line default
            #line hidden
            
            #line 145 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 if(commentAlreadyWritten == false) { 
            
            #line default
            #line hidden
            this.Write("           //Foreign Key List\r\n\t\t   \r\n");
            
            #line 147 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 commentAlreadyWritten = true;} 
            
            #line default
            #line hidden
            this.Write("           Create.");
            
            #line 148 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    if(!string.IsNullOrEmpty(fkey.Name)) 
    { 
        
            
            #line default
            #line hidden
            this.Write("ForeignKey(\"");
            
            #line 151 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 151 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    } 
            
            #line default
            #line hidden
            this.Write(".FromTable(\"");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.ForeignTableSchema));
            
            #line default
            #line hidden
            this.Write("\").ForeignColumns(");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.ForeignColumns)));
            
            #line default
            #line hidden
            this.Write(").ToTable(\"");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTable));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTableSchema));
            
            #line default
            #line hidden
            this.Write("\").PrimaryColumns(");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.PrimaryColumns)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 152 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetUpdateDeleteRule(fkey)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 153 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}
}
//for removed tables, remove the foreign keys, indexes, and tables themselves
foreach (Table removedTable in IgnoreInfo.Where(t => tables.All(tbl => tbl.Name != t.Name)))
{
foreach(ForeignKey fkey in removedTable.ForeignKeys)
    {
if(!string.IsNullOrEmpty(fkey.Name)){

            
            #line default
            #line hidden
            this.Write("            Delete.ForeignKey(\"");
            
            #line 163 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 163 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 163 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(removedTable.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 163 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 163 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write("; \r\n");
            
            #line 164 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

        } else {
        
            
            #line default
            #line hidden
            this.Write("            Delete.ForeignKey().FromTable(\"");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.ForeignTableSchema));
            
            #line default
            #line hidden
            this.Write("\").ForeignColumns(");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.ForeignColumns)));
            
            #line default
            #line hidden
            this.Write(").ToTable(\"");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTable));
            
            #line default
            #line hidden
            this.Write("\")/*.InSchema(\"");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTableSchema));
            
            #line default
            #line hidden
            this.Write("\")*/.PrimaryColumns(");
            
            #line 167 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.PrimaryColumns)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 168 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

        }
    }

	foreach(TableIndex idx in removedTable.Indexes)
    {

            
            #line default
            #line hidden
            this.Write("            Delete.Index(\"");
            
            #line 175 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idx.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 175 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 175 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(removedTable.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 175 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 175 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 176 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

    }


            
            #line default
            #line hidden
            this.Write("            Delete.Table(\"");
            
            #line 180 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(removedTable.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 181 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

} //Begin writing the Down migration

            
            #line default
            #line hidden
            this.Write("        }\r\n\t\t\r\n        public override void Down()\r\n        {\r\n");
            
            #line 188 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

var DeleteTableList = tables.Where(tbl => IgnoreInfo.All(t => t.Name != tbl.Name)).ToArray();
//Handle removing foreign keys generated in added tables, and add and delete foreign keys for changed tables
foreach(Table tbl in tables)
{
    Table otherTable = IgnoreInfo.SingleOrDefault(ot => ot.Name == tbl.Name);
	List<ForeignKey> FKeyList = tbl.ForeignKeys;
	if (otherTable != null)
	{
		FKeyList = FKeyList.Where(nfk => otherTable.ForeignKeys.All(ofk => ofk.Name != nfk.Name)).ToList();

		var addFKeyList = otherTable.ForeignKeys.Where(ofk => tbl.ForeignKeys.All(nfk => nfk.Name != ofk.Name)).ToList();
		foreach (ForeignKey addKey in addFKeyList)
		{
		
            
            #line default
            #line hidden
            this.Write("           Create.");
            
            #line 203 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    if(!string.IsNullOrEmpty(addKey.Name)) 
    { 
        
            
            #line default
            #line hidden
            this.Write("ForeignKey(\"");
            
            #line 206 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(addKey.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 206 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    } 
            
            #line default
            #line hidden
            this.Write(".FromTable(\"");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(addKey.ForeignTableSchema));
            
            #line default
            #line hidden
            this.Write("\").ForeignColumns(");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(addKey.ForeignColumns)));
            
            #line default
            #line hidden
            this.Write(").ToTable(\"");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(addKey.PrimaryTable));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(addKey.PrimaryTableSchema));
            
            #line default
            #line hidden
            this.Write("\").PrimaryColumns(");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(addKey.PrimaryColumns)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 207 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetUpdateDeleteRule(addKey)));
            
            #line default
            #line hidden
            this.Write(";\r\n        ");
            
            #line 208 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

		}
	}
    foreach(ForeignKey fkey in FKeyList)
    {
if(!string.IsNullOrEmpty(fkey.Name)){

            
            #line default
            #line hidden
            this.Write("            Delete.ForeignKey(\"");
            
            #line 215 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 215 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 215 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(tbl.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 215 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 215 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write("; \r\n");
            
            #line 216 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

        } else {
        
            
            #line default
            #line hidden
            this.Write("            Delete.ForeignKey().FromTable(\"");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.ForeignTableSchema));
            
            #line default
            #line hidden
            this.Write("\").ForeignColumns(");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.ForeignColumns)));
            
            #line default
            #line hidden
            this.Write(").ToTable(\"");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTable));
            
            #line default
            #line hidden
            this.Write("\")/*.InSchema(\"");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTableSchema));
            
            #line default
            #line hidden
            this.Write("\")*/.PrimaryColumns(");
            
            #line 219 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.PrimaryColumns)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 220 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

        }
    }
}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 226 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

//delete added tables
foreach(Table tbl in DeleteTableList)
{
	foreach(TableIndex idx in from i in tbl.Indexes select i)
    {

            
            #line default
            #line hidden
            this.Write("            Delete.Index(\"");
            
            #line 233 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idx.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 233 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 233 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(tbl.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 233 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 233 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 234 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 239 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

DeleteTableList = DeleteTableList.Reverse().ToArray();
foreach(Table tbl in DeleteTableList)
{

            
            #line default
            #line hidden
            this.Write("            Delete.Table(\"");
            
            #line 244 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tbl.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 245 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 249 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

//for shared tables, delete and add columns
foreach (Table afterTable in tables.Where(nt => IgnoreInfo.Any(ot => ot.Name == nt.Name)))
{
    Table beforeTable = IgnoreInfo.Single(ot => ot.Name == afterTable.Name);

	var colsToAdd = beforeTable.Columns.Where(bc => afterTable.Columns.All(ac => ac.Name != bc.Name)).ToArray();
	if (colsToAdd.Any())
	{

            
            #line default
            #line hidden
            this.Write("            Alter.Table(\"");
            
            #line 259 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(afterTable.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"dbo\")");
            
            #line 259 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

		foreach (Column newCol in colsToAdd)
		{

            
            #line default
            #line hidden
            this.Write("\r\n                .AddColumn(\"");
            
            #line 264 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(newCol.Name));
            
            #line default
            #line hidden
            this.Write("\").");
            
            #line 264 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetMigrationTypeFunctionForType(newCol)));
            
            #line default
            #line hidden
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (newCol.IsPrimaryKey){
            
            #line default
            #line hidden
            this.Write(".PrimaryKey()");
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (newCol.IsAutoIncrement){
            
            #line default
            #line hidden
            this.Write(".Identity()");
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (newCol.IsNullable){
            
            #line default
            #line hidden
            this.Write(".Nullable()");
            
            #line 265 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
else {
            
            #line default
            #line hidden
            this.Write(".NotNullable()");
            
            #line 266 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 266 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (newCol.DefaultValue != null || !newCol.IsNullable){
            
            #line default
            #line hidden
            
            #line 266 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetColumnDefaultValue(newCol)));
            
            #line default
            #line hidden
            
            #line 266 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 267 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

		}

            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 271 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

	}

            
            #line default
            #line hidden
            
            #line 274 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

	foreach (Column oldCol in afterTable.Columns.Where(ac => beforeTable.Columns.All(bc => bc.Name != ac.Name)))
	{

            
            #line default
            #line hidden
            this.Write("\t\t\tDelete.Column(\"");
            
            #line 278 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldCol.Name));
            
            #line default
            #line hidden
            this.Write("\").FromTable(\"");
            
            #line 278 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(afterTable.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"dbo\");\r\n");
            
            #line 279 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

	}

            
            #line default
            #line hidden
            
            #line 282 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 286 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
	//create tables that were deleted in the up migration
	foreach (Table oldTable in IgnoreInfo.Where(ot => tables.All(nt => nt.Name != ot.Name)))
	{

            
            #line default
            #line hidden
            this.Write("            Create.Table(\"");
            
            #line 290 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldTable.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 290 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(oldTable.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 290 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldTable.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 290 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 290 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

    var ColumnList = from c in oldTable.Columns where !c.Ignore select c;
foreach(Column col in ColumnList)
{

            
            #line default
            #line hidden
            this.Write("\r\n                .WithColumn(\"");
            
            #line 296 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\").");
            
            #line 296 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetMigrationTypeFunctionForType(col)));
            
            #line default
            #line hidden
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsPrimaryKey){
            
            #line default
            #line hidden
            this.Write(".PrimaryKey()");
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsAutoIncrement){
            
            #line default
            #line hidden
            this.Write(".Identity()");
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsNullable){
            
            #line default
            #line hidden
            this.Write(".Nullable()");
            
            #line 297 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
else {
            
            #line default
            #line hidden
            this.Write(".NotNullable()");
            
            #line 298 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 298 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.DefaultValue != null){
            
            #line default
            #line hidden
            
            #line 298 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetColumnDefaultValue(col)));
            
            #line default
            #line hidden
            
            #line 298 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 299 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 303 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

    List<TableIndex> IndexList = oldTable.Indexes;
foreach(TableIndex indx in IndexList)
{

            
            #line default
            #line hidden
            this.Write("            Create.Index(\"");
            
            #line 308 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indx.Name));
            
            #line default
            #line hidden
            this.Write("\").OnTable(\"");
            
            #line 308 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldTable.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 308 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (string.IsNullOrEmpty(oldTable.Schema) == false ){
            
            #line default
            #line hidden
            this.Write(".InSchema(\"");
            
            #line 308 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldTable.Schema));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 308 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 309 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

foreach(IndexColumn col in indx.IndexColumns)
{

            
            #line default
            #line hidden
            this.Write("\r\n                .OnColumn(\"");
            
            #line 314 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 314 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (col.IsAsc){
            
            #line default
            #line hidden
            this.Write(".Ascending()");
            
            #line 314 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}else{
            
            #line default
            #line hidden
            this.Write(".Descending()");
            
            #line 314 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            
            #line 315 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            
            #line 317 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
if (indx.IsUnique){

            
            #line default
            #line hidden
            this.Write("\r\n                .WithOptions().Unique()");
            
            #line 320 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
}
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 321 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}

            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n");
            
            #line 325 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

	}

	//create foreign keys for deleted tables
	foreach(Table oldTable in IgnoreInfo.Where(ot => tables.All(nt => nt.Name != ot.Name)))
{
    foreach(ForeignKey fkey in oldTable.ForeignKeys)
{

            
            #line default
            #line hidden
            this.Write("           Create.");
            
            #line 334 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    if(!string.IsNullOrEmpty(fkey.Name)) 
    { 
        
            
            #line default
            #line hidden
            this.Write("ForeignKey(\"");
            
            #line 337 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 337 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
 
    } 
            
            #line default
            #line hidden
            this.Write(".FromTable(\"");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(oldTable.Name));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.ForeignTableSchema));
            
            #line default
            #line hidden
            this.Write("\").ForeignColumns(");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.ForeignColumns)));
            
            #line default
            #line hidden
            this.Write(").ToTable(\"");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTable));
            
            #line default
            #line hidden
            this.Write("\").InSchema(\"");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fkey.PrimaryTableSchema));
            
            #line default
            #line hidden
            this.Write("\").PrimaryColumns(");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Join(fkey.PrimaryColumns)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 338 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generator.GetUpdateDeleteRule(fkey)));
            
            #line default
            #line hidden
            this.Write(";\r\n        ");
            
            #line 339 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\InitialMigrationCode.tt"

}
}

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 21 "C:\SalusSource\SmithBurgess\Development\Model\Src\Migration\NativeMigration\fluentmigrator\src\FluentMigrator.T4.GenerateMigration\FM.Core.ttinclude"


/* 
 This T4 code is created by Guru Kathiresan - gururamnath att yahoo.com
 -----------------------------------------------------------------------------------------

 This code is adapted from PetaPoco project (http://www.toptensoftware.com/petapoco).
 -----------------------------------------------------------------------------------------

 This template can read minimal schema information from the following databases:

    * SQL Server
    * SQL Server CE
    * MySQL
    * PostGreSQL
    * Oracle

 For connection and provider settings the template will look for the web.config or app.config file of the 
 containing Visual Studio project.  It will not however read DbProvider settings from this file.

 In order to work, the appropriate driver must be registered in the system machine.config file.  If you're
 using Visual Studio 2010 the file you want is here:

    C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config

 After making changes to machine.config you will also need to restart Visual Studio.

 Here's a typical set of entries that might help if you're stuck:

    <system.data>
        <DbProviderFactories>
            <add name="Odbc Data Provider" invariant="System.Data.Odbc" description=".Net Framework Data Provider for Odbc" type="System.Data.Odbc.OdbcFactory, System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <add name="OleDb Data Provider" invariant="System.Data.OleDb" description=".Net Framework Data Provider for OleDb" type="System.Data.OleDb.OleDbFactory, System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <add name="OracleClient Data Provider" invariant="System.Data.OracleClient" description=".Net Framework Data Provider for Oracle" type="System.Data.OracleClient.OracleClientFactory, System.Data.OracleClient, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <add name="SqlClient Data Provider" invariant="System.Data.SqlClient" description=".Net Framework Data Provider for SqlServer" type="System.Data.SqlClient.SqlClientFactory, System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.3.4.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d"/>
            <add name="Microsoft SQL Server Compact Data Provider" invariant="System.Data.SqlServerCe.3.5" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=3.5.1.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"/><add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"/>
            <add name="Npgsql Data Provider" invariant="Npgsql" support="FF" description=".Net Framework Data Provider for Postgresql Server" type="Npgsql.NpgsqlFactory, Npgsql, Version=2.0.11.91, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" />
        </DbProviderFactories>
    </system.data>

 Also, the providers and their dependencies need to be installed to GAC.  

 Eg; this is how I installed the drivers for PostgreSQL

     gacutil /i Npgsql.dll
     gacutil /i Mono.Security.dll

 -----------------------------------------------------------------------------------------
 
 SubSonic - http://subsonicproject.com
 
 The contents of this file are subject to the New BSD
 License (the "License"); you may not use this file
 except in compliance with the License. You may obtain a copy of
 the License at http://www.opensource.org/licenses/bsd-license.php
 
 Software distributed under the License is distributed on an 
 "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 implied. See the License for the specific language governing
 rights and limitations under the License.
*/

string ConnectionStringName = "";
string Namespace = "";
string PocoNamespace = "";
string RepoName = "";
string ClassPrefix = "";
string ClassSuffix = "";
string SchemaName = null;
bool IncludeViews = false;
bool GenerateOperations = false;
bool GenerateSeperateOperations = true;
bool GenerateCommon = true;
bool GeneratePocos = true;
bool TrackModifiedColumns = false;
List<string> IgnoreTableList = new List<string>();
string TableToGenerate = "";

string GetConnectionString(ref string connectionStringName, out string providerName)
{
    providerName=null;
    string result="";

    var connSection = ConfigurationManager.ConnectionStrings;

    //if the connectionString is empty - which is the defauls
    //look for count-1 - this is the last connection string
    //and takes into account AppServices and LocalSqlServer
    if(string.IsNullOrEmpty(connectionStringName))
    {
        if(connSection.Count>1)
        {
            connectionStringName = connSection[connSection.Count-1].Name;
            result=connSection[connSection.Count-1].ConnectionString;
            providerName=connSection[connSection.Count-1].ProviderName;
        }            
    }
    else
    {
        try
        {
            result=connSection[connectionStringName].ConnectionString;
            providerName=connSection[connectionStringName].ProviderName;
        }
        catch
        {
            result="There is no connection string name called '"+connectionStringName+"'";
        }
    }   
    return result;
}

string _connectionString="";
string _providerName="";

void InitConnectionString()
{
    if(String.IsNullOrEmpty(_connectionString))
    {
        _connectionString=GetConnectionString(ref ConnectionStringName, out _providerName);
    }
}

public string ConnectionString
{
    get 
    {
        InitConnectionString();
        return _connectionString;
    }
}

public string ProviderName
{
    get 
    {
        InitConnectionString();
        return _providerName;
    }
}

public Tables IgnoreInfo { get; set; }

private string _timeStamp;

public string GetCurrentTimeStamp()
{
    return _timeStamp ?? (_timeStamp = DateTime.Now.ToString("yyyyMMddhhmmss"));
}

    public string Join(IEnumerable<string> list)
{
    return System.String.Join(",", list.Select(l=>"\""+l+"\"").ToArray());
}


public void SaveOutput(string outputFileName)
{
    string templateDirectory = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
    string outputFilePath = Path.Combine(templateDirectory, outputFileName);
    File.WriteAllText(outputFilePath, this.GenerationEnvironment.ToString()); 
    this.GenerationEnvironment.Remove(0, this.GenerationEnvironment.Length);
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class InitialMigrationCodeBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
